// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/patient.proto

package patientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientRequest) Reset() {
	*x = PatientRequest{}
	mi := &file_proto_patient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientRequest) ProtoMessage() {}

func (x *PatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientRequest.ProtoReflect.Descriptor instead.
func (*PatientRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_proto_rawDescGZIP(), []int{0}
}

func (x *PatientRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type PatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientResponse) Reset() {
	*x = PatientResponse{}
	mi := &file_proto_patient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientResponse) ProtoMessage() {}

func (x *PatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientResponse.ProtoReflect.Descriptor instead.
func (*PatientResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_proto_rawDescGZIP(), []int{1}
}

func (x *PatientResponse) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *PatientResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatientResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_proto_patient_proto protoreflect.FileDescriptor

const file_proto_patient_proto_rawDesc = "" +
	"\n" +
	"\x13proto/patient.proto\x12\apatient\"/\n" +
	"\x0ePatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"V\n" +
	"\x0fPatientResponse\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age2Q\n" +
	"\x0ePatientService\x12?\n" +
	"\n" +
	"GetPatient\x12\x17.patient.PatientRequest\x1a\x18.patient.PatientResponseB\x11Z\x0fproto/patientpbb\x06proto3"

var (
	file_proto_patient_proto_rawDescOnce sync.Once
	file_proto_patient_proto_rawDescData []byte
)

func file_proto_patient_proto_rawDescGZIP() []byte {
	file_proto_patient_proto_rawDescOnce.Do(func() {
		file_proto_patient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_patient_proto_rawDesc), len(file_proto_patient_proto_rawDesc)))
	})
	return file_proto_patient_proto_rawDescData
}

var file_proto_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_patient_proto_goTypes = []any{
	(*PatientRequest)(nil),  // 0: patient.PatientRequest
	(*PatientResponse)(nil), // 1: patient.PatientResponse
}
var file_proto_patient_proto_depIdxs = []int32{
	0, // 0: patient.PatientService.GetPatient:input_type -> patient.PatientRequest
	1, // 1: patient.PatientService.GetPatient:output_type -> patient.PatientResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_patient_proto_init() }
func file_proto_patient_proto_init() {
	if File_proto_patient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_patient_proto_rawDesc), len(file_proto_patient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_patient_proto_goTypes,
		DependencyIndexes: file_proto_patient_proto_depIdxs,
		MessageInfos:      file_proto_patient_proto_msgTypes,
	}.Build()
	File_proto_patient_proto = out.File
	file_proto_patient_proto_goTypes = nil
	file_proto_patient_proto_depIdxs = nil
}
